##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/python-caja
    - aptitude
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - gcc
    - git
    - gtk-doc-tools
    - libcaja-extension-dev
    - libgirepository1.0-dev
    - make
    - mate-common
    - python3-dev
    - python-gi-dev
    - quilt

before_scripts:
  - ./html-cppcheck

build_scripts:
  - ./before-build
  - ./make-scanbuild '--enable-compile-warnings=maximum'
  - ./after-build

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20; fi
