##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:

before_scripts:
  - ./debrepo-install

build_scripts:
  - ./build-debs

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20; fi
